- name: 🟢 Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # ⚡ Gracias al package-lock.json, esto ahora volará

      - name: 📚 Install dependencies
        run: npm ci # 🚀 Instalación ultra rápida y segura
